// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMWOZ4bCKIe4Mlue_6UN9O49qyGGK5xjE',
    appId: '1:355145901897:web:c7af479064c540dc92dc98',
    messagingSenderId: '355145901897',
    projectId: 'mynotes-flutter-92099',
    authDomain: 'mynotes-flutter-92099.firebaseapp.com',
    storageBucket: 'mynotes-flutter-92099.appspot.com',
    measurementId: 'G-FK2V8MG3HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfDbuDyV9xa76k82YaH14iwAW4bYeokD0',
    appId: '1:355145901897:android:60d6f296cfdc32ee92dc98',
    messagingSenderId: '355145901897',
    projectId: 'mynotes-flutter-92099',
    storageBucket: 'mynotes-flutter-92099.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiG1AL682WaNcMo8uowhjgeq1iQGrZ3V4',
    appId: '1:355145901897:ios:234cf4c87194b06d92dc98',
    messagingSenderId: '355145901897',
    projectId: 'mynotes-flutter-92099',
    storageBucket: 'mynotes-flutter-92099.appspot.com',
    iosBundleId: 'com.simgit.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiG1AL682WaNcMo8uowhjgeq1iQGrZ3V4',
    appId: '1:355145901897:ios:825f919a67407ffc92dc98',
    messagingSenderId: '355145901897',
    projectId: 'mynotes-flutter-92099',
    storageBucket: 'mynotes-flutter-92099.appspot.com',
    iosBundleId: 'com.simgit.mynotes.RunnerTests',
  );
}
